os: osx
language: swift
osx_image: xcode8.2

script: 
  - set -o pipefail
  - xcodebuild -workspace 'Games.xcworkspace' -scheme 'Games' -configuration 'Debug' -sdk iphonesimulator -destination 'name=iPhone 6s' build test | xcpretty -c
